-- ============================================================
-- ZOMATO SQL DATA ANALYTICS PROJECT
-- MySQL 8+
-- ============================================================

-- 1. USER-DEFINED FUNCTION
-- Returns the requested "Chicken Quick Bites" label.
DROP FUNCTION IF EXISTS fn_chicken_quick_bites;

DELIMITER //
CREATE FUNCTION fn_chicken_quick_bites()
RETURNS VARCHAR(100)
DETERMINISTIC
BEGIN
    RETURN 'Chicken Quick Bites';
END //
DELIMITER ;

SELECT
    restaurant_name,
    fn_chicken_quick_bites() AS stuffed_type
FROM zomato;


-- 2. RESTAURANT + CUISINE WITH MAXIMUM NUMBER OF RATINGS/VOTES
SELECT
    restaurant_name,
    cuisines,
    votes
FROM zomato
WHERE votes = (SELECT MAX(votes) FROM zomato);


-- 3. RATING STATUS
SELECT
    restaurant_name,
    rating,
    CASE
        WHEN rating > 4 THEN 'Excellent'
        WHEN rating > 3.5 THEN 'Good'
        WHEN rating > 3 THEN 'Average'
        ELSE 'Bad'
    END AS rating_status
FROM zomato;


-- 4. NUMERIC FUNCTIONS + CURRENT DATE PARTS
SELECT
    rating,
    CEIL(rating) AS rating_ceil,
    FLOOR(rating) AS rating_floor,
    ABS(rating) AS rating_abs,
    CURDATE() AS current_date,
    YEAR(CURDATE()) AS year,
    MONTHNAME(CURDATE()) AS month_name,
    DAY(CURDATE()) AS day
FROM zomato;


-- 5. RESTAURANT TYPE + AVERAGE COST USING ROLLUP
SELECT
    restaurant_type,
    AVG(average_cost_for_two) AS avg_cost
FROM zomato
GROUP BY restaurant_type WITH ROLLUP;


-- OPTIONAL: Replace NULL generated by ROLLUP with a readable label
SELECT
    COALESCE(restaurant_type, 'GRAND TOTAL') AS restaurant_type,
    AVG(average_cost_for_two) AS avg_cost
FROM zomato
GROUP BY restaurant_type WITH ROLLUP;
